// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESP32BACKEND.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20251114192604_attractionSeed")]
    partial class attractionSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Attractions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Attractions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArDescription = "سوق الكتب التاريخي والشارع الثقافي في بغداد.",
                            ArName = "شارع المتنبي",
                            Description = "Historic book market and cultural street in Baghdad.",
                            ImageUrl = "/img/attractions/baghdad_mutanabbi.jpg",
                            Location = "Baghdad",
                            Name = "Al-Mutanabbi Street",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArDescription = "كورنيش وشاطئ منطقة ميناء البصرة.",
                            ArName = "كورنيش شط العرب",
                            Description = "Riverside promenade and port area in Basra.",
                            ImageUrl = "/img/attractions/basra_shatt.jpg",
                            Location = "Basra",
                            Name = "Shatt al-Arab Promenade",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArDescription = "قلعة قديمة تطل على الموصل ونهر دجلة.",
                            ArName = "قلعة الموصل",
                            Description = "Ancient citadel overlooking Mosul and the Tigris.",
                            ImageUrl = "/img/attractions/mosul_citadel.jpg",
                            Location = "Mosul",
                            Name = "Mosul Citadel",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArDescription = "قلعة مدرجة في لائحة اليونسكو وسط أربيل.",
                            ArName = "قلعة أربيل",
                            Description = "UNESCO-listed citadel in the heart of Erbil.",
                            ImageUrl = "/img/attractions/erbil_citadel.jpg",
                            Location = "Erbil",
                            Name = "Erbil Citadel",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArDescription = "متحف ونصب تذكاري تاريخي في السليمانية.",
                            ArName = "أمنا سوراكا",
                            Description = "Historical museum and memorial in Sulaymaniyah.",
                            ImageUrl = "/img/attractions/sulaymaniyah_amna.jpg",
                            Location = "Sulaymaniyah",
                            Name = "Amna Suraka",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArDescription = "سد ومنطقة نزهة خلابة قرب دهوك.",
                            ArName = "سد دهوك",
                            Description = "Scenic dam and picnic area near Duhok.",
                            ImageUrl = "/img/attractions/duhok_dam.jpg",
                            Location = "Duhok",
                            Name = "Duhok Dam",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArDescription = "قلعة تاريخية ومنطقة المدينة القديمة في كركوك.",
                            ArName = "قلعة كركوك",
                            Description = "Historic citadel and old city area in Kirkuk.",
                            ImageUrl = "/img/attractions/kirkuk_citadel.jpg",
                            Location = "Kirkuk",
                            Name = "Kirkuk Citadel",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArDescription = "مستنقعات واسعة تقدم رحلات طبيعية.",
                            ArName = "أهوار الأنبار",
                            Description = "Vast marshlands and wetlands offering nature excursions.",
                            ImageUrl = "/img/attractions/anbar_marshes.jpg",
                            Location = "Anbar",
                            Name = "Anbar Marshes",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArDescription = "مواقع تاريخية ومناطق على الواجهة النهريّة حول تكريت.",
                            ArName = "قلعة تكريت",
                            Description = "Historical sites and riverfront areas around Tikrit.",
                            ImageUrl = "/img/attractions/tikrit_castle.jpg",
                            Location = "Tikrit",
                            Name = "Tikrit Castle",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArDescription = "أسواق تقليدية وواجهة نهرية في محافظة ديالى.",
                            ArName = "الحي التاريخي خانقين",
                            Description = "Traditional markets and riverside in Diyala governorate.",
                            ImageUrl = "/img/attractions/diyala_khanaqin.jpg",
                            Location = "Diyala",
                            Name = "Khanaqin Historic Quarter",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArDescription = "الحي التاريخي والواجهة النهرية في واسط.",
                            ArName = "المدينة القديمة الكوت",
                            Description = "Historical district and riverside in Wasit.",
                            ImageUrl = "/img/attractions/wasit_kut.jpg",
                            Location = "Wasit",
                            Name = "Kut Old Town",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 12,
                            ArDescription = "أطلال بابل القديمة قرب الحلة الحديثة.",
                            ArName = "بابل الأثرية",
                            Description = "Ruins of ancient Babylon near modern-day Hillah.",
                            ImageUrl = "/img/attractions/babil_babylon.jpg",
                            Location = "Babil",
                            Name = "Ancient Babylon",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 13,
                            ArDescription = "موقع حج رئيسي وضريح مقدس في كربلاء.",
                            ArName = "ضريح الإمام الحسين",
                            Description = "Major pilgrimage site and holy shrine in Karbala.",
                            ImageUrl = "/img/attractions/karbala_shrine.jpg",
                            Location = "Karbala",
                            Name = "Imam Husayn Shrine",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 14,
                            ArDescription = "ضريح مقدس ومركز حج في النجف.",
                            ArName = "ضريح الإمام علي",
                            Description = "Holy shrine and pilgrimage center in Najaf.",
                            ImageUrl = "/img/attractions/najaf_shrine.jpg",
                            Location = "Najaf",
                            Name = "Imam Ali Shrine",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 15,
                            ArDescription = "حدائق محلية ومناطق تاريخية في القادسية.",
                            ArName = "حدائق الديوانية",
                            Description = "Local parks and historical areas in Qadisiyyah.",
                            ImageUrl = "/img/attractions/qadisiyyah_gardens.jpg",
                            Location = "Qadisiyyah",
                            Name = "Diwaniyah Gardens",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 16,
                            ArDescription = "مناظر صحراوية ومواقع أثرية في المثنى.",
                            ArName = "منطقة صحراء المثنى",
                            Description = "Desert landscapes and archaeological sites in Muthanna.",
                            ImageUrl = "/img/attractions/muthanna_desert.jpg",
                            Location = "Muthanna",
                            Name = "Sami al-Sabhan Desert Area",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 17,
                            ArDescription = "الأهوار الميسوبوتامية ومواقع ثقافية في ذي قار.",
                            ArName = "مستنقعات الناصرية",
                            Description = "Mesopotamian marshes and cultural sites in Dhi Qar.",
                            ImageUrl = "/img/attractions/dhiqar_marshes.jpg",
                            Location = "Dhi Qar",
                            Name = "Nasiriyah Marshlands",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 18,
                            ArDescription = "كورنيش و أسواق في مدينة العمارة بمحافظة ميسان.",
                            ArName = "كورنيش العمارة",
                            Description = "Riverside promenade and marketplaces in Maysan.",
                            ImageUrl = "/img/attractions/maysan_amarah.jpg",
                            Location = "Maysan",
                            Name = "Amarah Waterfront",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 19,
                            ArDescription = "حديقة نصب تذكاري ومتحف في محافظة حلبجة.",
                            ArName = "حديقة ذكرى حلبجة",
                            Description = "Memorial park and museum in Halabja province.",
                            ImageUrl = "/img/attractions/halabja_memorial.jpg",
                            Location = "Halabja",
                            Name = "Halabja Memorial Park",
                            ProvinceId = 19
                        });
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArName = "بغداد",
                            Name = "Baghdad",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArName = "البصرة",
                            Name = "Basra",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArName = "الزبير",
                            Name = "Az Zubayr",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            ArName = "الموصل",
                            Name = "Mosul",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 5,
                            ArName = "تلعفر",
                            Name = "Tal Afar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            ArName = "أربيل",
                            Name = "Erbil",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 7,
                            ArName = "سوران",
                            Name = "Soran",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            ArName = "السليمانية",
                            Name = "Sulaymaniyah",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 9,
                            ArName = "چمچمال",
                            Name = "Chamchamal",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            ArName = "دهوك",
                            Name = "Duhok",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 11,
                            ArName = "زاخو",
                            Name = "Zakho",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 12,
                            ArName = "كركوك",
                            Name = "Kirkuk",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 13,
                            ArName = "الرمادي",
                            Name = "Ramadi",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 14,
                            ArName = "الفلوجة",
                            Name = "Fallujah",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 15,
                            ArName = "تكريت",
                            Name = "Tikrit",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 16,
                            ArName = "بعقوبة",
                            Name = "Baqubah",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 17,
                            ArName = "الكوت",
                            Name = "Kut",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 18,
                            ArName = "الحلة",
                            Name = "Hilla",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 19,
                            ArName = "كربلاء",
                            Name = "Karbala",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 20,
                            ArName = "النجف",
                            Name = "Najaf",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 21,
                            ArName = "الديوانية",
                            Name = "Diwaniyah",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 22,
                            ArName = "السماوة",
                            Name = "Samawah",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 23,
                            ArName = "الناصرية",
                            Name = "Nasiriyah",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 24,
                            ArName = "العمارة",
                            Name = "Amarah",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 25,
                            ArName = "حلبجة",
                            Name = "Halabja",
                            ProvinceId = 19
                        });
                });

            modelBuilder.Entity("Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArDescription = "عاصمة العراق.",
                            ArName = "بغداد",
                            Area = 455.0,
                            Description = "Capital of Iraq.",
                            ImageUrl = "/img/baghdad.jpg",
                            Name = "Baghdad",
                            Population = 8000000
                        },
                        new
                        {
                            Id = 2,
                            ArDescription = "مدينة ميناء رئيسية في جنوب العراق.",
                            ArName = "البصرة",
                            Area = 19070.0,
                            Description = "Major port city in southern Iraq.",
                            ImageUrl = "/img/basra.jpg",
                            Name = "Basra",
                            Population = 2900000
                        },
                        new
                        {
                            Id = 3,
                            ArDescription = "محافظة تحتوي على الموصل.",
                            ArName = "نينوى",
                            Area = 37323.0,
                            Description = "Province containing Mosul.",
                            ImageUrl = "/img/nineveh.jpg",
                            Name = "Nineveh",
                            Population = 4000000
                        },
                        new
                        {
                            Id = 4,
                            ArDescription = "عاصمة إقليم كردستان.",
                            ArName = "أربيل",
                            Area = 15074.0,
                            Description = "Capital of the Kurdistan Region.",
                            ImageUrl = "/img/erbil.jpg",
                            Name = "Erbil",
                            Population = 2000000
                        },
                        new
                        {
                            Id = 5,
                            ArDescription = "محافظة في إقليم كردستان.",
                            ArName = "السليمانية",
                            Area = 17023.0,
                            Description = "Kurdistan Region province.",
                            ImageUrl = "/img/sulaymaniyah.jpg",
                            Name = "Sulaymaniyah",
                            Population = 2000000
                        },
                        new
                        {
                            Id = 6,
                            ArDescription = "محافظة شمالية في كردستان.",
                            ArName = "دهوك",
                            Area = 6553.0,
                            Description = "Northern province of Kurdistan.",
                            ImageUrl = "/img/duhok.jpg",
                            Name = "Duhok",
                            Population = 1300000
                        },
                        new
                        {
                            Id = 7,
                            ArDescription = "محافظة غنية بالنفط ومتنوعة.",
                            ArName = "كركوك",
                            Area = 9679.0,
                            Description = "Oil-rich, diverse province.",
                            ImageUrl = "/img/kirkuk.jpg",
                            Name = "Kirkuk",
                            Population = 1600000
                        },
                        new
                        {
                            Id = 8,
                            ArDescription = "أكبر محافظة من حيث المساحة.",
                            ArName = "الأنبار",
                            Area = 138501.0,
                            Description = "Largest province by area.",
                            ImageUrl = "/img/anbar.jpg",
                            Name = "Anbar",
                            Population = 1700000
                        },
                        new
                        {
                            Id = 9,
                            ArDescription = "محافظة تحتوي على تكريت.",
                            ArName = "صلاح الدين",
                            Area = 24363.0,
                            Description = "Province containing Tikrit.",
                            ImageUrl = "/img/salahaldin.jpg",
                            Name = "Salah al-Din",
                            Population = 1600000
                        },
                        new
                        {
                            Id = 10,
                            ArDescription = "محافظة شرق بغداد.",
                            ArName = "ديالى",
                            Area = 17685.0,
                            Description = "Province east of Baghdad.",
                            ImageUrl = "/img/diyala.jpg",
                            Name = "Diyala",
                            Population = 1600000
                        },
                        new
                        {
                            Id = 11,
                            ArDescription = "محافظة عاصمتها الكوت.",
                            ArName = "واسط",
                            Area = 17153.0,
                            Description = "Province with capital Kut.",
                            ImageUrl = "/img/wasit.jpg",
                            Name = "Wasit",
                            Population = 1400000
                        },
                        new
                        {
                            Id = 12,
                            ArDescription = "محافظة تحتوي على بابل القديمة.",
                            ArName = "بابل",
                            Area = 5119.0,
                            Description = "Province containing ancient Babylon.",
                            ImageUrl = "/img/babil.jpg",
                            Name = "Babil",
                            Population = 2200000
                        },
                        new
                        {
                            Id = 13,
                            ArDescription = "مدينة مقدسة للشيعة.",
                            ArName = "كربلاء",
                            Area = 5034.0,
                            Description = "Holy city for Shia Muslims.",
                            ImageUrl = "/img/karbala.jpg",
                            Name = "Karbala",
                            Population = 1200000
                        },
                        new
                        {
                            Id = 14,
                            ArDescription = "مدينة مقدسة ذات أهمية دينية.",
                            ArName = "النجف",
                            Area = 28823.0,
                            Description = "Holy city with religious significance.",
                            ImageUrl = "/img/najaf.jpg",
                            Name = "Najaf",
                            Population = 1600000
                        },
                        new
                        {
                            Id = 15,
                            ArDescription = "محافظة عاصمتها الديوانية.",
                            ArName = "القادسية",
                            Area = 8153.0,
                            Description = "Province with capital Diwaniyah.",
                            ImageUrl = "/img/qadisiyyah.jpg",
                            Name = "Qadisiyyah",
                            Population = 1300000
                        },
                        new
                        {
                            Id = 16,
                            ArDescription = "محافظة صحراوية جنوبية.",
                            ArName = "المثنى",
                            Area = 51740.0,
                            Description = "Southern desert province.",
                            ImageUrl = "/img/muthanna.jpg",
                            Name = "Muthanna",
                            Population = 850000
                        },
                        new
                        {
                            Id = 17,
                            ArDescription = "محافظة تحتوي على الناصرية.",
                            ArName = "ذي قار",
                            Area = 12900.0,
                            Description = "Province containing Nasiriyah.",
                            ImageUrl = "/img/dhiqar.jpg",
                            Name = "Dhi Qar",
                            Population = 2100000
                        },
                        new
                        {
                            Id = 18,
                            ArDescription = "محافظة شرق العراق.",
                            ArName = "ميسان",
                            Area = 16072.0,
                            Description = "Province east of Iraq.",
                            ImageUrl = "/img/maysan.jpg",
                            Name = "Maysan",
                            Population = 1100000
                        },
                        new
                        {
                            Id = 19,
                            ArDescription = "أحدث محافظة عراقية.",
                            ArName = "حلبجة",
                            Area = 1598.0,
                            Description = "Newest Iraqi province.",
                            ImageUrl = "/img/halabja.jpg",
                            Name = "Halabja",
                            Population = 400000
                        });
                });

            modelBuilder.Entity("Attractions", b =>
                {
                    b.HasOne("Province", "Province")
                        .WithMany("Attractions")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.HasOne("Province", "Province")
                        .WithMany("Cards")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("City", b =>
                {
                    b.HasOne("Province", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Province", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Cards");

                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
